name: Branch Protection Check

on:
  pull_request:
    branches: [develop]

permissions:
  contents: read

jobs:
  branch_protection:
    name: branch_protection
    runs-on: ubuntu-latest
    steps:
      - name: Branch protection check
        run: echo "Branch protection check passed." 